block: introduce ZEN I/O scheduler
It is the default I/O scheduler in n7000's kernel branch lineage-16.0, as per time of commit.
Also, included a fix to resolve compilation error: https://github.com/leewp14/android_kernel_samsung_smdk4412/commit/94adb1a196a5a801c17cfdc483890e9c1b070408

Change-Id: I2d1dbd4bec1799c63335ad69b67bf152adee2e67